### ISSUE TITLE
Find Peers With Broker Node

### ISSUE THREAD

**Issue by furesoft** [Krzysztofz01/Noise#2]
Does this library the possibility to find other peers over the internet by asking a special node that is reachable on the internet?

**Comment by Krzysztofz01** [comment]
Due to the fact that this is the early development stage of this protocol and the project, the functionality of discovering is very limited. I plan to implement something in the style of  a **"tracker"** (known from torrents), which will index peers. Of course, the use of it will be optional. The host itself will also be able to start in the **"Relay mode"**, i.e. it will passively index endpoints and transmit discovery packets.
